export const domesticFlightData = [
  {
    airline: '에어서울',
    flightNumber: '901',
    departure: '김포 (GMP)',
    departureTime: '2025-09-16 06:00',
    arrival: '제주 (CJU)',
    arrivalTime: '2025-09-16 07:15',
    cabinClass: '할인석',
    seatStatus: 'HK',
  },
  {
    airline: '진에어',
    flightNumber: '516',
    departure: '제주 (CJU)',
    departureTime: '2025-09-27 21:15',
    arrival: '김포 (GMP)',
    arrivalTime: '2025-09-27 22:30',
    cabinClass: '할인석',
    seatStatus: 'HK',
  },
];

export const internationalFlightData = [
  {
    airnm: '대한항공',
    fltno: '17',
    depcity: '서울',
    depairport: 'ICN',
    depdate: '2025-12-01',
    deptm: '14:30',
    arrcity: '로스앤젤레스',
    arrairport: 'LAX',
    arrdate: '2025-12-01',
    arrtm: '08:30',
    cabinclass: '일반석',
    baggage: '2개',
  },
  {
    airnm: '유나이티드항공',
    fltno: '391',
    depcity: '로스앤젤레스',
    depairport: 'LAX',
    depdate: '2025-12-31',
    deptm: '07:21',
    arrcity: '샌프란시스코',
    arrairport: 'SFO',
    arrdate: '2025-12-31',
    arrtm: '08:48',
    cabinclass: '일반석',
    baggage: '0개',
  },
  {
    airnm: '유나이티드항공',
    fltno: '1995',
    depcity: '샌프란시스코',
    depairport: 'SFO',
    depdate: '2026-01-29',
    deptm: '19:10',
    arrcity: '라스베이거스',
    arrairport: 'LAS',
    arrdate: '2026-01-29',
    arrtm: '20:43',
    cabinclass: '일반석',
    baggage: '2개',
  },
  {
    airnm: '대한항공',
    fltno: '6',
    depcity: '라스베이거스',
    depairport: 'LAS',
    depdate: '2026-02-27',
    deptm: '22:50',
    arrcity: '서울',
    arrairport: 'ICN',
    arrdate: '2026-03-01',
    arrtm: '05:20',
    cabinclass: '일반석',
    baggage: '2개',
  },
];

export const flightGraphData = [
  {
    itinno: '1', //
    segno: '1', //
    aircd: 'KE',
    airnm: '대한항공', //
    fltno: '17', //
    depcitynm: '서울', //
    depairportnm: '인천', //
    depdate: '20251201', //
    deptm: '1430', //
    arrcitynm: '로스앤젤레스', //
    arrairportcd: 'LAX', //
    arrdate: '20251201', //
    arrtm: '0830', //
    bookingclass: 'Y',
    cabinclassnm: '일반석',
    baggageinfo: '2개',
    codeshare: '',
    codesharenm: '',
  },
  {
    itinno: '2',
    segno: '1',
    aircd: 'UA',
    airnm: '유나이티드항공',
    fltno: '391',
    depcitynm: '로스앤젤레스',
    depdate: '20251231',
    deptm: '0721',
    arrcitynm: '샌프란시스코',
    arrdate: '20251231',
    arrtm: '0848',
    bookingclass: 'Q',
    cabinclassnm: '일반석',
    baggageinfo: '2개',
    codeshare: '',
    codesharenm: '',
  },
  {
    itinno: '3',
    segno: '1',
    aircd: 'UA',
    airnm: '유나이티드항공',
    fltno: '1995',
    depcitynm: '샌프란시스코',
    depdate: '20260129',
    deptm: '1910',
    arrcitynm: '라스베이거스',
    arrdate: '20260129',
    arrtm: '2043',
    bookingclass: 'Q',
    cabinclassnm: '일반석',
    baggageinfo: '2개',
    codeshare: '',
    codesharenm: '',
  },
  {
    itinno: '4',
    segno: '1',
    aircd: 'KE',
    airnm: '대한항공',
    fltno: '7532',
    depcitynm: '라스베이거스',
    depdate: '20260227',
    deptm: '1950',
    arrcitynm: '로스앤젤레스',
    arrdate: '20260227',
    arrtm: '2110',
    bookingclass: 'Y',
    cabinclassnm: '일반석',
    baggageinfo: '2개',
    codeshare: 'DL',
    codesharenm: '델타항공',
  },
  {
    itinno: '4',
    segno: '2',
    aircd: 'KE',
    airnm: '대한항공',
    fltno: '12',
    depcitynm: '로스앤젤레스',
    depdate: '20260227',
    deptm: '2240',
    arrcitynm: '서울',
    arrairportnm: '인천',
    arrdate: '20260301',
    arrtm: '0450',
    bookingclass: 'Y',
    cabinclassnm: '일반석',
    baggageinfo: '2개',
    codeshare: '',
    codesharenm: '',
  },
];
